# Generated by Django 3.0.3 on 2020-03-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='direccion',
            field=models.CharField(max_length=50),
        ),
    ]
