# Generated by Django 3.0.3 on 2020-03-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_autor_libro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['titulo'], 'verbose_name_plural': 'Libros'},
        ),
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(null=True, upload_to='portadas'),
        ),
    ]
